# Generated by Django 5.1.2 on 2024-11-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_enrollrement_date_user_enrollment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enrollment_date',
            new_name='enrollrement_date',
        ),
    ]
