# Generated by Django 5.1.2 on 2024-11-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_enrollment_date_user_enrollrement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enrollrement_date',
            new_name='enrollment_date',
        ),
    ]
